//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Table
    {
        public int Client_ID { get; set; }
        public string Client_FirstName { get; set; }
        public string Client_LastName { get; set; }
        public string Client_Phone { get; set; }
        public string Client_Address { get; set; }
    }
}
