//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation_Table
    {
        public int Reservation_ID { get; set; }
        public string Reservation_Room_Type { get; set; }
        public int Reservation_Room_Number { get; set; }
        public int Reservation_Client_ID { get; set; }
        public string Reservation_In { get; set; }
        public string Reservation_Out { get; set; }
    }
}
