//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room_Table
    {
        public int Room_Number { get; set; }
        public string Room_Type { get; set; }
        public string Room_Phone { get; set; }
        public string Room_Free { get; set; }
    }
}
